#!/bin/bash

if [[ "$1" != "status" ]]; then
	echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
fi
PACKAGE_BASE=${TRIM_APPDEST}
PACKAGE_SHARE="/var/apps/grafana.alloy/shares/grafana.alloy"
EXEC_BIN="${PACKAGE_BASE}/app/alloy-linux"
#EXEC_ARGS=" --storage.path=${PACKAGE_SHARE}/storage --server.http.listen-addr=0.0.0.0:12345 ${PACKAGE_SHARE}/config.alloy.conf"
EXEC_ARGS=" --storage.path=${PACKAGE_SHARE}/storage ${PACKAGE_SHARE}/config.alloy.conf"
LOG_DIR="${PACKAGE_SHARE}"
LOG_FILE="${LOG_DIR}/grafana.alloy.log"

EXEC_CMDLINE="${EXEC_BIN} run ${EXEC_ARGS}"

case $1 in
start)
	processNum=$(pgrep -c alloy-linux)
	if [[ ! $processNum -eq 0 ]]; then
		echo "is already running"
		exit 0
	else
	  [ -f ${PACKAGE_SHARE}/config.alloy.conf ] || cp ${PACKAGE_BASE}/app/config.alloy.conf.template ${PACKAGE_SHARE}/config.alloy.conf
	  mkdir -m 777 -p ${LOG_DIR}

		CPU_COUNT=$(nproc)
    BIND_COUNT=4
    [ "$CPU_COUNT" -lt "$BIND_COUNT" ] && BIND_COUNT="$CPU_COUNT"
    START_CPU=$((CPU_COUNT - BIND_COUNT))
    CPU_LIST=""
    for i in $(seq 0 $((BIND_COUNT - 1))); do
				CPU_LIST="${CPU_LIST}$((START_CPU + i)),"
    done
    CPU_LIST=${CPU_LIST%,}

		echo "taskset -c ${CPU_LIST} ${EXEC_CMDLINE}"
		echo -e "$(date +'%Y/%m/%d %H:%M:%S') clear log" > ${LOG_FILE}
		nohup taskset -c ${CPU_LIST} ${EXEC_CMDLINE} >>${LOG_FILE} 2>&1 &
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
			exit 0
		else
			exit 1
		fi
	fi
	;;
stop)
	pkill -9 alloy-linux || echo "pkill fail $?"
	;;
status)
	processNum=$(pgrep -c alloy-linux)
	if [[ ! $processNum -eq 0 ]]; then
		#echo "is already running"
		exit 0
	else
	  echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
	  echo "is not running"
		exit 3
	fi
	;;
*)
	exit 1
	;;
esac